[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which chromium) npm start"

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
